sudo: required
dist: xenial
language: go
go:
  - 1.5
services: docker

cache:
  directories:
    - node_modules

before_install:
  - docker run carlad/sinatra -v /dev/shm:/dev/sh
  - sudo apt-get install -y chromium-browser  # Travis version needs updating

install:
  - ls -alt $HOME/.ssh

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  - cd tests
  - ./run-tests.sh snapweb localhost 8022

