sudo: required
dist: xenial
language: go
go:
- 1.5
cache:
  directories:
  - node_modules
addons:
  ssh_known_hosts: 162.213.35.217
before_install:
  - openssl aes-256-cbc -K $encrypted_b2c18e2f704c_key -iv $encrypted_b2c18e2f704c_iv -in id_rsa_snapweb_no_pswd.enc -out id_rsa_snapweb_no_pswd -d 
  - rm id_rsa_snapweb_no_pswd.enc
  - chmod 600 id_rsa_snapweb_no_pswd
  - mv id_rsa_snapweb_no_pswd.enc ~/.ssh/id_rsa
install:
- sudo apt remove -y chromium-browser
- sudo apt-get install -y  google-chrome-stable
- ls -alt $HOME/.ssh
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
script:
- cd tests
- "./run-tests.sh snapweb-ci 162.213.35.217 22"
