sudo: required
dist: trusty
language: go
go:
  - 1.5

cache:
  directories:
    - node_modules

before_install:
  - openssl aes-256-cbc -K $encrypted_730d54c061db_key -iv $encrypted_730d54c061db_iv -in id_rsa.enc -out id_rsa -d
  - sudo apt remove -y chromium-browser
  - sudo apt-get install -y  google-chrome-stable

install:
  - mkdir -p $HOME/.ssh
  - mv id_rsa $HOME/.ssh
  - chmod 600 $HOME/.ssh/id_rsa
  - ls -alt $HOME/.ssh

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  - cat ssh-config-tweak >> ~/.ssh/config
  - cd tests
  - ./run-tests.sh snapweb.ci 104.199.9.196 22

