sudo: required
dist: xenial
language: go
go:
  - 1.5

cache:
  directories:
    - node_modules

before_install:

install:
  - sudo apt remove -y chromium-browser
  - sudo apt-get install -y  google-chrome-stable qemu-kvm xdotool
  - ls -alt $HOME/.ssh

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  - ./setup-kvm.sh ubuntu-core-16-amd64.img.xz
  - cd tests
  - ./run-tests.sh snapweb localhost 8022

